export const MOVIES = [
    {
        "dates": { "maximum": "2021-10-03", "minimum": "2021-08-16" },
        "page": 1, 
        "results": [
            { "adult": false, "backdrop_path": "/8Y43POKjjKDGI9MH89NW0NAzzp8.jpg", "genre_ids": [35, 28, 12, 878], "id": 550988, "original_language": "en", "original_title": "Free Guy", "overview": "A bank teller called Guy realizes he is a background character in an open world video game called Free City that will soon go offline.", "popularity": 11516.441, "poster_path": "/xmbU4JTUm8rsdtn7Y3Fcm30GpeT.jpg", "release_date": "2021-08-11", "title": "Free Guy", "video": false, "vote_average": 7.9, "vote_count": 2061 },
            { "adult": false, "backdrop_path": "/aO9Nnv9GdwiPdkNO79TISlQ5bbG.jpg", "genre_ids": [28, 12], "id": 568620, "original_language": "en", "original_title": "Snake Eyes: G.I. Joe Origins", "overview": "After saving the life of their heir apparent, tenacious loner Snake Eyes is welcomed into an ancient Japanese clan called the Arashikage where he is taught the ways of the ninja warrior. But, when secrets from his past are revealed, Snake Eyes' honor and allegiance will be tested – even if that means losing the trust of those closest to him.", "popularity": 6273.394, "poster_path": "/uIXF0sQGXOxQhbaEaKOi2VYlIL0.jpg", "release_date": "2021-07-22", "title": "Snake Eyes: G.I. Joe Origins", "video": false, "vote_average": 6.9, "vote_count": 568 },
            { "adult": false, "backdrop_path": "/vkIJ2QgcKMJRvi6pBW4Tr2kgLdy.jpg", "genre_ids": [80, 53], "id": 637534, "original_language": "fr", "original_title": "BAC Nord", "overview": "A police brigade working in the dangerous northern neighborhoods of Marseille, where the level of crime is higher than anywhere else in France.", "popularity": 3560.227, "poster_path": "/nLanxl7Xhfbd5s8FxPy8jWZw4rv.jpg", "release_date": "2021-08-18", "title": "The Stronghold", "video": false, "vote_average": 7.8, "vote_count": 373 },
            { "adult": false, "backdrop_path": "/t9nyF3r0WAlJ7Kr6xcRYI4jr9jm.jpg", "genre_ids": [878, 28], "id": 580489, "original_language": "en", "original_title": "Venom: Let There Be Carnage", "overview": "After finding a host body in investigative reporter Eddie Brock, the alien symbiote must face a new enemy, Carnage, the alter ego of serial killer Cletus Kasady.", "popularity": 4238.873, "poster_path": "/rjkmN1dniUHVYAtwuV3Tji7FsDO.jpg", "release_date": "2021-09-30", "title": "Venom: Let There Be Carnage", "video": false, "vote_average": 7.5, "vote_count": 164 },
            { "adult": false, "backdrop_path": "/iDLtDgxLiYsarfdQ4msUhUqoNPp.jpg", "genre_ids": [878], "id": 725273, "original_language": "en", "original_title": "Solitary", "overview": "A man wakes up inside a room to discover he's a prisoner sent into space to form Earth's first colony, and worse - his cell mate Alana is hell bent on destroying everything.", "popularity": 2109.94, "poster_path": "/ApwmbrMlsuOay5rXQA4Kbz7qJAl.jpg", "release_date": "2021-09-24", "title": "Solitary", "video": false, "vote_average": 6.5, "vote_count": 26 },
            { "adult": false, "backdrop_path": "/iTgM25ftE7YtFgZwUZupVp8A61S.jpg", "genre_ids": [27, 9648, 53], "id": 631843, "original_language": "en", "original_title": "Old", "overview": "A group of families on a tropical holiday discover that the secluded beach where they are staying is somehow causing them to age rapidly – reducing their entire lives into a single day.", "popularity": 1492.621, "poster_path": "/vclShucpUmPhdAOmKgf3B3Z4POD.jpg", "release_date": "2021-07-21", "title": "Old", "video": false, "vote_average": 6.7, "vote_count": 1069 },
            { "adult": false, "backdrop_path": "/cinER0ESG0eJ49kXlExM0MEWGxW.jpg", "genre_ids": [28, 12, 14], "id": 566525, "original_language": "en", "original_title": "Shang-Chi and the Legend of the Ten Rings", "overview": "Shang-Chi must confront the past he thought he left behind when he is drawn into the web of the mysterious Ten Rings organization.", "popularity": 1771.916, "poster_path": "/1BIoJGKbXjdFDAqUEiA2VHqkK1Z.jpg", "release_date": "2021-09-01", "title": "Shang-Chi and the Legend of the Ten Rings", "video": false, "vote_average": 7.8, "vote_count": 1171 },
            { "adult": false, "backdrop_path": "/MDYanFolbT76dj0gsCbhS2GM5A.jpg", "genre_ids": [37, 28], "id": 859860, "original_language": "en", "original_title": "Catch the Bullet", "overview": "U.S. marshal Britt MacMasters returns from a mission to find his father wounded and his son kidnapped by the outlaw Jed Blake. Hot on their trail, Britt forms a posse with a gunslinging deputy and a stoic Pawnee tracker. But Jed and Britt tread dangerously close to the Red Desert’s Sioux territory.", "popularity": 1358.659, "poster_path": "/qKxrBZ8Ts4KHZKp7BT6GAVMLFO2.jpg", "release_date": "2021-09-10", "title": "Catch the Bullet", "video": false, "vote_average": 5.7, "vote_count": 46 },
            { "adult": false, "backdrop_path": "/jlGmlFOcfo8n5tURmhC7YVd4Iyy.jpg", "genre_ids": [28, 12, 14, 35], "id": 436969, "original_language": "en", "original_title": "The Suicide Squad", "overview": "Supervillains Harley Quinn, Bloodsport, Peacemaker and a collection of nutty cons at Belle Reve prison join the super-secret, super-shady Task Force X as they are dropped off at the remote, enemy-infused island of Corto Maltese.", "popularity": 1627.55, "poster_path": "/kb4s0ML0iVZlG6wAKbbs9NAm6X.jpg", "release_date": "2021-07-28", "title": "The Suicide Squad", "video": false, "vote_average": 7.8, "vote_count": 4220 },
            { "adult": false, "backdrop_path": "/7WJjFviFBffEJvkAms4uWwbcVUk.jpg", "genre_ids": [12, 14, 35, 28], "id": 451048, "original_language": "en", "original_title": "Jungle Cruise", "overview": "Dr. Lily Houghton enlists the aid of wisecracking skipper Frank Wolff to take her down the Amazon in his dilapidated boat. Together, they search for an ancient tree that holds the power to heal – a discovery that will change the future of medicine.", "popularity": 1505.346, "poster_path": "/9dKCd55IuTT5QRs989m9Qlb7d2B.jpg", "release_date": "2021-07-28", "title": "Jungle Cruise", "video": false, "vote_average": 7.8, "vote_count": 2825 },
            { "adult": false, "backdrop_path": "/pUc51UUQb1lMLVVkDCaZVsCo37U.jpg", "genre_ids": [53, 27], "id": 482373, "original_language": "en", "original_title": "Don't Breathe 2", "overview": "The Blind Man has been hiding out for several years in an isolated cabin and has taken in and raised a young girl orphaned from a devastating house fire. Their quiet life together is shattered when a group of criminals kidnap the girl, forcing the Blind Man to leave his safe haven to save her.", "popularity": 1254.203, "poster_path": "/hRMfgGFRAZIlvwVWy8DYJdLTpvN.jpg", "release_date": "2021-08-12", "title": "Don't Breathe 2", "video": false, "vote_average": 7.7, "vote_count": 870 },
            { "adult": false, "backdrop_path": "/byflnwPMumyvrCW9SfO5Miq3647.jpg", "genre_ids": [28, 53], "id": 597891, "original_language": "en", "original_title": "Kate", "overview": "After she's irreversibly poisoned, a ruthless criminal operative has less than 24 hours to exact revenge on her enemies and in the process forms an unexpected bond with the daughter of one of her past victims.", "popularity": 1201.429, "poster_path": "/uJgdT1boTSP0dDIjdTgGleg71l4.jpg", "release_date": "2021-09-10", "title": "Kate", "video": false, "vote_average": 6.8, "vote_count": 574 },
            { "adult": false, "backdrop_path": "/xXHZeb1yhJvnSHPzZDqee0zfMb6.jpg", "genre_ids": [28, 80, 53], "id": 385128, "original_language": "en", "original_title": "F9", "overview": "Dominic Toretto and his crew battle the most skilled assassin and high-performance driver they've ever encountered: his forsaken brother.", "popularity": 1420.771, "poster_path": "/bOFaAXmWWXC3Rbv4u4uM9ZSzRXP.jpg", "release_date": "2021-05-19", "title": "F9", "video": false, "vote_average": 7.5, "vote_count": 3916 },
            { "adult": false, "backdrop_path": "/akwg1s7hV5ljeSYFfkw7hTHjVqk.jpg", "genre_ids": [16, 35, 12, 10751], "id": 459151, "original_language": "en", "original_title": "The Boss Baby: Family Business", "overview": "The Templeton brothers — Tim and his Boss Baby little bro Ted — have become adults and drifted away from each other. But a new boss baby with a cutting-edge approach and a can-do attitude is about to bring them together again … and inspire a new family business.", "popularity": 1126.161, "poster_path": "/uWStkK8bq9ixY3fc7y209ZleCoF.jpg", "release_date": "2021-07-01", "title": "The Boss Baby: Family Business", "video": false, "vote_average": 7.7, "vote_count": 1463 },
            { "adult": false, "backdrop_path": "/3GgkzCDq6KYpcmJmcOKh27hYRyj.jpg", "genre_ids": [12, 16, 10751, 14], "id": 588921, "original_language": "en", "original_title": "Ainbo: Spirit of the Amazon", "overview": "An epic journey of a young hero and her Spirit Guides, 'Dillo' a cute and humorous armadillo and \"Vaca\" a goofy oversized tapir, who embark on a quest to save their home in the spectacular Amazon Rainforest.", "popularity": 1246.571, "poster_path": "/l8HyObVj8fPrzacAPtGWWLDhcfh.jpg", "release_date": "2021-02-09", "title": "Ainbo: Spirit of the Amazon", "video": false, "vote_average": 7.2, "vote_count": 186 },
            { "adult": false, "backdrop_path": "/mtRW6eAwOO27h3zrfU2foQFW7Hg.jpg", "genre_ids": [16, 10751, 12, 35], "id": 675445, "original_language": "en", "original_title": "PAW Patrol: The Movie", "overview": "Ryder and the pups are called to Adventure City to stop Mayor Humdinger from turning the bustling metropolis into a state of chaos.", "popularity": 985.641, "poster_path": "/ic0intvXZSfBlYPIvWXpU1ivUCO.jpg", "release_date": "2021-08-09", "title": "PAW Patrol: The Movie", "video": false, "vote_average": 7.8, "vote_count": 560 },
            { "adult": false, "backdrop_path": "/ugukqzx4gSzBd1yzmbWEHLkpGaS.jpg", "genre_ids": [16, 10751, 14, 35, 10402, 12], "id": 597316, "original_language": "en", "original_title": "My Little Pony: A New Generation", "overview": "Equestria's divided. But a bright-eyed hero believes Earth Ponies, Pegasi and Unicorns should be pals — and, hoof to heart, she’s determined to prove it.", "popularity": 1154.384, "poster_path": "/hzq5XRGgm6NDMOW1idUvbpGqEkv.jpg", "release_date": "2021-09-23", "title": "My Little Pony: A New Generation", "video": false, "vote_average": 8.1, "vote_count": 81 },
            { "adult": false, "backdrop_path": "/8s4h9friP6Ci3adRGahHARVd76E.jpg", "genre_ids": [16, 35, 10751, 878], "id": 379686, "original_language": "en", "original_title": "Space Jam: A New Legacy", "overview": "When LeBron and his young son Dom are trapped in a digital space by a rogue A.I., LeBron must get them home safe by leading Bugs, Lola Bunny and the whole gang of notoriously undisciplined Looney Tunes to victory over the A.I.'s digitized champions on the court. It's Tunes versus Goons in the highest-stakes challenge of his life.", "popularity": 1018.077, "poster_path": "/5bFK5d3mVTAvBCXi5NPWH0tYjKl.jpg", "release_date": "2021-07-08", "title": "Space Jam: A New Legacy", "video": false, "vote_average": 7.3, "vote_count": 2336 },
            { "adult": false, "backdrop_path": "/gzppdxEJ6fofhtLzSVSUJZEVxvq.jpg", "genre_ids": [28, 878, 53], "id": 848278, "original_language": "en", "original_title": "Jurassic Hunt", "overview": "Female adventurer Parker joins a crew of male trophy hunters in a remote wilderness park. Their goal: slaughter genetically recreated dinosaurs for sport using rifles, arrows, and grenades. After their guide is killed by raptors, the team tries to escape the park – but the hunters quickly become the hunted. Even worse, the park’s manager suspects Parker of being a spy and sends a hit squad after her. This battle’s about to become primitive!", "popularity": 913.808, "poster_path": "/bZnOioDq1ldaxKfUoj3DenHU7mp.jpg", "release_date": "2021-08-26", "title": "Jurassic Hunt", "video": false, "vote_average": 4.9, "vote_count": 140 },
            { "adult": false, "backdrop_path": "/620hnMVLu6RSZW6a5rwO8gqpt0t.jpg", "genre_ids": [16, 35, 10751, 14], "id": 508943, "original_language": "en", "original_title": "Luca", "overview": "Luca and his best friend Alberto experience an unforgettable summer on the Italian Riviera. But all the fun is threatened by a deeply-held secret: they are sea monsters from another world just below the water’s surface.", "popularity": 1005.722, "poster_path": "/8tABCBpzu3mZbzMB3sRzMEHEvJi.jpg", "release_date": "2021-06-17", "title": "LUCAAAAAAA", "video": false, "vote_average": 8, "vote_count": 4706 }], "total_pages": 86, "total_results": 1707
    }
]